title:  "Example slide"
author: "sue445"

meta_properties:
  og:type: "website"
  og:title: "Example slide"
  og:description: "Example slide"
  og:url: "https://sue445.github.io/reveal-ck-example/#/"
  og:image: "https://sue445.github.io/reveal-ck-example/images/sue445.png"

meta_names:
  twitter:card: "summary"
  twitter:site: "@sue445"
  twitter:creator: "@sue445"
  twitter:title: "Example slide"
  twitter:description: "Example slide"
  twitter:image: "https://sue445.github.io/reveal-ck-example/images/sue445.png"
